# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXSKJ9UTcoA2YAp3xrVBgu1VQksOO5m5
"""

import pandas as pd
import numpy as np
import matplotlib as plt

df = pd.read_excel("/content/final cleaned dataset.xlsx")

df.head()

df['totalprice'].max()

df['totalprice'].min()

df['totalprice'].mean()

df['totalprice'].sum()

df['quantity'].mean()

df['itemsincart'].max()

df['itemsincart'].min()

df['quantity'].max()

df.groupby('product')['totalprice'].sum()

df.groupby('paymentmethod')['totalprice'].sum()

product_sales = df.groupby('product')['totalprice'].sum()
product_sales.sort_values(ascending=False)

df['product'].value_counts().head(1)

df['product'].value_counts().tail(1)

df['orderstatus'].value_counts()

df['paymentmethod'].value_counts()

df['referralsource'].value_counts()

df.groupby('referralsource')['totalprice'].sum()

df['date'] = pd.to_datetime(df['date'])
df['date']

df['month']=df['date'].dt.month
df['month'].head()

df['year']=df['date'].dt.year
df['year'].head()

df.groupby('month')['totalprice'].sum()

df.groupby('year')['totalprice'].sum()

import matplotlib.pyplot as plt
import seaborn as sns

product_sales.sort_values(ascending=False).plot(kind='bar', figsize=(8,4))
plt.title("Revenue by Product")
plt.xlabel("product")
plt.ylabel("revenue")
plt.show()

df['paymentmethod'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(6,6)
)
plt.title("Payment Method Distribution")
plt.ylabel("")
plt.show()

df['product'].value_counts().plot(kind='bar',figsize=(6,3))
plt.title("Total Product")
plt.xlabel("product")
plt.ylabel("total")
plt.show()

monthly_sales = df.groupby('month')['totalprice'].sum()
monthly_sales.plot(kind='line', marker='o', figsize=(4,3))
plt.title("Monthly Sales Trend")
plt.xlabel("month")
plt.ylabel("sales")
plt.show()

yearly_sales = df.groupby('year')['totalprice'].sum()
yearly_sales.plot(kind='bar', figsize=(4,3))
plt.title("Yearly Sales")
plt.xlabel("year")
plt.ylabel("sales")
plt.show()

df['orderstatus'].value_counts().plot(kind='bar', figsize=(4,3))
plt.title("Order Status Count")
plt.xlabel("orderstatus")
plt.ylabel("count")
plt.show()

df['paymentmethod'].value_counts().plot(kind='bar', figsize=(4,3))
plt.title("Payment Method Count")
plt.xlabel("paymentmethod")
plt.ylabel("count")
plt.show()

product_sales.idxmax()

df['paymentmethod'].value_counts().idxmax()

df['orderstatus'].value_counts().idxmax()

df['referralsource'].value_counts().idxmax()

monthly_sales.idxmax()