# -*- coding: utf-8 -*-
"""Task1_DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h9rs5_T1g_mQ_JvhHejIt3z02hudWk-m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('/content/raw_data.xlsx')

df.head()

df.info()

df.size

df.describe()

df.columns

"""# CHECK MISSING VALUES

"""

df.isnull().sum()

"""CHECK DUPLICATE ROWS"""

df.duplicated().sum()

"""HANDLE MISSING VALUES"""

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
  df[col] = df[col].fillna(df[col].median())

categorical_cols = df.select_dtypes(include=['object', 'string']).columns
for col in categorical_cols:
  df[col] = df[col].fillna(df[col].mode()[0])

"""REMOVE DUPLICATES"""

df.drop_duplicates(inplace = True)

"""STANDARDIZE COLUMN NAMES"""

df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.columns

"""CLEAN TEXT DATA"""

categorical_cols = df.select_dtypes(include=['object', 'string']).columns
for col in categorical_cols:
  df[col] = df[col].astype(str).str.strip().str.title()

"""DATE CONVERSION"""

for col in df.columns:
  if 'date' in col:
    df[col] = pd.to_datetime(df[col], errors='coerce')

"""REMOVE INVALID VALUES

"""

numeric_cols = df.select_dtypes(include=np.number).columns
for col in numeric_cols:
  df = df[df[col] >= 0]

"""VERIFY TOTAL PRICE CALCULATION"""

df['calculated_total'] = df['quantity'] * df['unitprice']

comparison = df['totalprice'] == df['calculated_total']
print("\nCorrect TotalPrice Rows:", comparison.sum())
df['totalprice'] = df['calculated_total']
df.drop(columns=['calculated_total'], inplace=True)

"""FINAL DATASET CHECK"""

df.isnull().sum()

df.dtypes

df.shape

"""SAVE CLEANED DATASET"""

df.to_excel("cleaned_dataset.xlsx", index=False)

from google.colab import files

files.download("cleaned_dataset.xlsx")